apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-staging
  namespace: argocd-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Using the official Nginx image from Docker Hub.
        ports:
        - containerPort: 80
