apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-application-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ajaymindtech/argocd-new-cicd.git'
    path: ARGOCD-CICD/environments/dev/app1
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd-deploy
  syncPolicy:
    automated: 
      selfHeal: true
      prune: true
